spring.application.name=sbnz-legal

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/sbnz
spring.datasource.username=sbnz
spring.datasource.password=sbnz
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

office.load.waitingThreshold=2
office.load.readyThreshold=2
case.inactivity.days=30
